import Link from "next/link";
import { notFound } from "next/navigation";
import { OperationsShell } from "@/app/components/operations-shell";
import { requirePermissionWithOrganization } from "@/lib/authorization";
import { withOrganizationContext } from "@/lib/tenant-context";

export default async function ContentAssetPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { session, organizationId } = await requirePermissionWithOrganization("content:manage");
  const { slug } = await params;
  const asset = await withOrganizationContext(organizationId, (tx) =>
    tx.contentAsset.findUnique({
      where: { slug },
      include: { job: { include: { template: true, requestedBy: true } } },
    }),
  );
  if (!asset) notFound();
  const formats = ["text", "html", "json", "png", "pdf"];
  return (
    <OperationsShell user={session.user}>
      <main className="mx-auto max-w-6xl px-6 py-10">
        <Link href="/content" className="text-sm text-text-2">Back to content studio</Link>
        <p className="mt-6 text-xs uppercase tracking-[.24em] text-brand-400">{asset.job.type.replaceAll("_", " ")}</p>
        <h1 className="mt-2 text-3xl font-semibold">{asset.title}</h1>
        <p className="mt-2 text-sm text-text-3">Generated by {asset.job.requestedBy.name} · {asset.createdAt.toLocaleString()} · {asset.job.template.name}</p>
        <div className="mt-6 flex flex-wrap gap-2">
          {formats.map((format) => <a key={format} href={`/content/assets/${slug}/export/${format}`} className="rounded-lg border border-line px-4 py-2 text-sm uppercase">{format}</a>)}
        </div>
        <div className="mt-8 grid gap-6 lg:grid-cols-2">
          <section className="rounded-lg border border-line bg-ink-800 p-5"><h2 className="font-semibold">Text</h2><pre className="mt-4 whitespace-pre-wrap font-sans text-sm text-text-1">{asset.textContent}</pre></section>
          <section className="overflow-hidden rounded-lg border border-line bg-white"><iframe sandbox="" title="HTML content preview" srcDoc={asset.htmlContent} className="h-[500px] w-full" /></section>
          <section className="lg:col-span-2 rounded-lg border border-line bg-ink-800 p-5"><h2 className="font-semibold">Graphic data</h2><pre className="mt-4 overflow-x-auto text-xs text-text-2">{JSON.stringify(asset.graphicData,null,2)}</pre></section>
        </div>
      </main>
    </OperationsShell>
  );
}
