// Basketball definition. Rule values mirror the legacy Ultra rules in src/lib/game-rules.ts
// (ULTRA_RULES) and the defaults on RuleSet/GameRuleSnapshot. See registry.test.ts for the
// parity assertions that keep this definition and the legacy constants in lockstep.

import type { SportDefinition } from "./types";

export const BASKETBALL: SportDefinition = {
  key: "BASKETBALL",
  slug: "basketball",
  name: "Basketball",
  version: 1,
  entities: ["TEAM"],
  structure: {
    periodType: "HALF",
    periodCount: 2,
    periodDurationSeconds: 600,
    overtimeDurationSeconds: 300,
    clock: "RUNNING",
    shotClockSeconds: 20,
  },
  scoring: {
    unit: "point",
    values: [1, 2, 3, 4],
    winCondition: "HIGHEST_SCORE",
    drawsAllowed: false,
  },
  events: [
    { key: "SHOT_MADE", label: "Shot made", category: "SCORING", scores: true, pointValues: [1, 2, 3, 4], producesMetrics: ["points", "fieldGoalsMade", "threePointsMade"] },
    { key: "SHOT_ATTEMPT", label: "Shot attempt", category: "SCORING", producesMetrics: ["fieldGoalsAttempted", "threePointsAttempted"] },
    { key: "SHOT_MISSED", label: "Shot missed", category: "SCORING" },
    { key: "FREE_THROW_MADE", label: "Free throw made", category: "SCORING", scores: true, pointValues: [1], producesMetrics: ["points", "freeThrowsMade"] },
    { key: "FREE_THROW_ATTEMPT", label: "Free throw attempt", category: "SCORING", producesMetrics: ["freeThrowsAttempted"] },
    { key: "FREE_THROW_MISSED", label: "Free throw missed", category: "SCORING" },
    { key: "OFFENSIVE_REBOUND", label: "Offensive rebound", category: "POSSESSION", producesMetrics: ["rebounds", "offensiveRebounds"] },
    { key: "DEFENSIVE_REBOUND", label: "Defensive rebound", category: "POSSESSION", producesMetrics: ["rebounds", "defensiveRebounds"] },
    { key: "ASSIST", label: "Assist", category: "POSSESSION", producesMetrics: ["assists"] },
    { key: "STEAL", label: "Steal", category: "DEFENCE", producesMetrics: ["steals"] },
    { key: "BLOCK", label: "Block", category: "DEFENCE", producesMetrics: ["blocks"] },
    { key: "TURNOVER", label: "Turnover", category: "POSSESSION", producesMetrics: ["turnovers"] },
    { key: "FOUL", label: "Foul", category: "DISCIPLINE", producesMetrics: ["fouls"] },
    { key: "TIMEOUT", label: "Timeout", category: "GAME_CONTROL" },
    { key: "SUBSTITUTION", label: "Substitution", category: "LINEUP" },
  ],
  metrics: [
    { key: "points", label: "Points", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "SCORING", derivedFromEventKeys: ["SHOT_MADE", "FREE_THROW_MADE"], sortOrder: 1 },
    { key: "rebounds", label: "Rebounds", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "POSSESSION", derivedFromEventKeys: ["OFFENSIVE_REBOUND", "DEFENSIVE_REBOUND"], sortOrder: 2 },
    { key: "assists", label: "Assists", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "POSSESSION", derivedFromEventKeys: ["ASSIST"], sortOrder: 3 },
    { key: "steals", label: "Steals", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "DEFENCE", derivedFromEventKeys: ["STEAL"], sortOrder: 4 },
    { key: "blocks", label: "Blocks", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "DEFENCE", derivedFromEventKeys: ["BLOCK"], sortOrder: 5 },
    { key: "turnovers", label: "Turnovers", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "POSSESSION", derivedFromEventKeys: ["TURNOVER"], sortOrder: 6 },
    { key: "fouls", label: "Fouls", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "DISCIPLINE", derivedFromEventKeys: ["FOUL"], sortOrder: 7 },
    { key: "minutesPlayed", label: "Minutes played", valueType: "DURATION", subject: "PLAYER", aggregation: "SUM", category: "GENERAL", sortOrder: 8 },
    { key: "fieldGoalsMade", label: "Field goals made", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "SCORING", sortOrder: 9 },
    { key: "fieldGoalsAttempted", label: "Field goals attempted", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "SCORING", sortOrder: 10 },
    { key: "threePointsMade", label: "Three points made", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "SCORING", sortOrder: 11 },
    { key: "threePointsAttempted", label: "Three points attempted", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "SCORING", sortOrder: 12 },
    { key: "freeThrowsMade", label: "Free throws made", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "SCORING", sortOrder: 13 },
    { key: "freeThrowsAttempted", label: "Free throws attempted", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "SCORING", sortOrder: 14 },
    { key: "offensiveRebounds", label: "Offensive rebounds", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "POSSESSION", sortOrder: 15 },
    { key: "defensiveRebounds", label: "Defensive rebounds", valueType: "COUNT", subject: "PLAYER", aggregation: "SUM", category: "POSSESSION", sortOrder: 16 },
    { key: "points", label: "Points", valueType: "COUNT", subject: "ENTRANT", aggregation: "SUM", category: "SCORING", sortOrder: 1 },
    { key: "rebounds", label: "Rebounds", valueType: "COUNT", subject: "ENTRANT", aggregation: "SUM", category: "POSSESSION", sortOrder: 2 },
    { key: "assists", label: "Assists", valueType: "COUNT", subject: "ENTRANT", aggregation: "SUM", category: "POSSESSION", sortOrder: 3 },
    { key: "turnovers", label: "Turnovers", valueType: "COUNT", subject: "ENTRANT", aggregation: "SUM", category: "POSSESSION", sortOrder: 4 },
    { key: "fouls", label: "Fouls", valueType: "COUNT", subject: "ENTRANT", aggregation: "SUM", category: "DISCIPLINE", sortOrder: 5 },
  ],
  standings: {
    outcomes: ["WIN", "LOSS"],
    primaryPoints: { model: "WIN_DRAW_LOSS", win: 3, draw: 0, loss: 0 },
    tiebreak: ["LEAGUE_POINTS", "WINS", "POINT_DIFFERENCE", "POINTS_FOR", "NAME"],
  },
  roster: {
    minRoster: 5,
    maxRoster: 15,
    activeCount: 5,
    substitutesAllowed: true,
    positions: ["Point guard", "Shooting guard", "Small forward", "Power forward", "Center"],
  },
  surface: { type: "COURT", lengthM: 28, widthM: 15 },
  capabilities: ["DRAFT", "SHOT_CLOCK", "ULTRA_TIME", "FOUR_POINT", "SUBSTITUTIONS", "SURFACE_VISION"],
  rules: [
    { key: "ULTRA_TIME_THRESHOLD_SECONDS", value: 60, label: "Ultra Time starts at" },
    { key: "ULTRA_TIME_MULTIPLIER", value: 2, label: "Ultra Time scoring multiplier" },
    { key: "FOUR_POINT_BASE_VALUE", value: 4, label: "Four-point shot value" },
    { key: "MANDATORY_SUBSTITUTION_POLICY", value: "AT_LEAST_ONE_PER_HALF", label: "Mandatory substitution policy" },
  ],
};
